# Example Traject extra config for EAD collection indexing.
# You can copy this file into Arclight (or a theme you have modifying Arclight,
# e.g., Arcuit):
# {arclight_dir}/lib/arcuit/traject/ead_extra_config.rb
#
# Any additional Traject commands you add to this file will be added to collection
# records in Arclight.
#
# This file shows the fields that arcflow injects into EAD XML to support:
# 1. Record group and sub-group categories
# 2. Solr ID for the creator records also created by arcflow
#
# GROUP + SUB-GROUP
# Arcflow adds <recordgroup> and <subgroup> elements directly after </did>
#   <recordgroup>ALA 52 — Library Periodicals Round Table</recordgroup>
#   <subgroup>ALA 52.2 — Publications</subgroup>
#
# CREATOR RECORDS
# Arcflow adds authfilenumber attributes to origination name elements:
#   <origination label="Creator">
#     <corpname source="lcnaf" authfilenumber="creator_corporate_entities_123">
#       ALA Allied Professional Association
#     </corpname>
#   </origination>
#

# Creator ArcLight IDs - extracted from authfilenumber attributes on origination
# name elements (<corpname>, <persname>, <famname>) injected by arcflow into EAC_CPF
# files generated by ArchivesSpace.
# Indexed as an array of creator IDs (e.g., ["creator_corporate_entities_123"])
# for bidirectional creator↔collection linking in Solr.
to_field 'creator_arclight_ids_ssim' do |record, accumulator|
  record.xpath('//ead:archdesc/ead:did/ead:origination/ead:corpname[@authfilenumber] |
                //ead:archdesc/ead:did/ead:origination/ead:persname[@authfilenumber] |
                //ead:archdesc/ead:did/ead:origination/ead:famname[@authfilenumber]',
               'ead' => 'urn:isbn:1-931666-22-9').each do |node|
    accumulator << node['authfilenumber']
  end
  # Also check without namespace (some ASpace EAD exports omit it)
  if accumulator.empty?
    record.xpath('//archdesc/did/origination/corpname[@authfilenumber] |
                  //archdesc/did/origination/persname[@authfilenumber] |
                  //archdesc/did/origination/famname[@authfilenumber]').each do |node|
      accumulator << node['authfilenumber']
    end
  end
end

# Record group and sub-group - extracted from recordgroup and subgroup elements
# injected by Arcflow into EAD documents created by ArchivesSpace
to_field 'record_group_ssim', extract_xpath('/ead/archdesc/recordgroup')
to_field 'subgroup_ssim', extract_xpath('/ead/archdesc/subgroup')
